import { NextResponse } from "next/server";
import { z } from "zod";
import { hashPassword } from "@/lib/auth/password";
import { passwordSchema, passwordStrength } from "@/lib/auth/users";
import { clearPasswordResetChallenge, getPasswordResetChallenge, otpMatches } from "@/lib/auth/password-reset";
import { withTransaction } from "@/lib/db";
import { clearLoginFailuresForIdentity } from "@/lib/security/rate-limit";

const schema=z.object({code:z.string().regex(/^\d{6}$/),password:passwordSchema,passwordConfirmation:z.string()}).refine(v=>v.password===v.passwordConfirmation,{path:["passwordConfirmation"],message:"Hai mật khẩu chưa trùng khớp."});
export async function POST(request:Request){ const id=await getPasswordResetChallenge(); if(!id)return NextResponse.json({error:"Yêu cầu đặt lại mật khẩu đã hết hạn. Hãy yêu cầu mã mới."},{status:400}); const parsed=schema.safeParse(await request.json().catch(()=>null)); if(!parsed.success||passwordStrength(parsed.data.password)==="weak")return NextResponse.json({error:parsed.success?"Mật khẩu cần đạt mức Trung bình trở lên.":parsed.error.flatten()},{status:400}); try { const email=await withTransaction(async client=>{ const reset=await client.query<{user_id:string;email:string;otp_hash:string;attempts:number;expires_at:string;consumed_at:string|null;status:string}>(`SELECT r.user_id,r.email,r.otp_hash,r.attempts,r.expires_at,r.consumed_at,u.status FROM password_reset_requests r JOIN users u ON u.id=r.user_id WHERE r.id=$1 FOR UPDATE`,[id]); const row=reset.rows[0]; if(!row||row.status!=="active"||row.consumed_at||new Date(row.expires_at)<=new Date())throw new Error("EXPIRED"); if(row.attempts>=5)throw new Error("LOCKED"); if(!otpMatches(id,parsed.data.code,row.otp_hash)){await client.query("UPDATE password_reset_requests SET attempts=attempts+1 WHERE id=$1",[id]);throw new Error("INVALID_CODE");} await client.query("UPDATE users SET password_hash=$1,session_version=session_version+1,updated_at=now() WHERE id=$2",[await hashPassword(parsed.data.password),row.user_id]); await client.query("UPDATE password_reset_requests SET consumed_at=now() WHERE id=$1",[id]); await client.query("INSERT INTO user_lifecycle_events(user_id,event_type,details) VALUES($1,'updated',$2::jsonb)",[row.user_id,JSON.stringify({passwordResetBy:"email_otp"})]); return row.email; }); await clearPasswordResetChallenge(); await clearLoginFailuresForIdentity(email); return NextResponse.json({ok:true}); } catch(error){ const code=error instanceof Error?error.message:""; if(code==="INVALID_CODE")return NextResponse.json({error:"Mã xác thực không đúng."},{status:400}); await clearPasswordResetChallenge(); return NextResponse.json({error:"Mã xác thực đã hết hạn hoặc không còn hiệu lực. Hãy yêu cầu mã mới."},{status:400}); } }
